"""24 plantillas de casos habituales en tableros TAN de telecomunicaciones CFT."""

from __future__ import annotations

from typing import Any


def _num(name: str, label: str, unit: str, default: float, step: float = 0.1) -> dict[str, Any]:
    return {"name": name, "label": label, "unit": unit, "type": "number", "default": default, "step": step}


def _sel(name: str, label: str, options: list[str], default: str) -> dict[str, Any]:
    return {"name": name, "label": label, "type": "select", "options": options, "default": default}


def _txt(name: str, label: str, default: str = "") -> dict[str, Any]:
    return {"name": name, "label": label, "type": "text", "default": default}


def _chk(name: str, label: str, default: bool = False) -> dict[str, Any]:
    return {"name": name, "label": label, "type": "checkbox", "default": default}


TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "T01",
        "name": "Bus 24 VDC del rack de telecomunicaciones",
        "category": "Medición",
        "iec": "IEC 61439-1 §5 condiciones de servicio · §10.10 calentamiento",
        "metric": "v_mean",
        "design_field": "v_nom",
        "tolerance_pct": 4.0,
        "summary": "Compara el CSV del Gratten en el bus del rack con la tensión de diseño 24 V.",
        "fields": [
            _num("v_nom", "Tensión de diseño", "V", 24.0),
            _num("ripple_max_pct", "Rizado máximo aceptable", "%", 2.0),
            _sel("fuente", "Fuente de pañol / sitio", ["wanptek KPS305D", "rectificador de rack", "otra"], "wanptek KPS305D"),
            _txt("rack_id", "Identificación del rack CFT", "RACK-TEL-01"),
        ],
        "voice": "Un bus continuo estable es la base silenciosa de un nodo TAN: la 61439-1 te pide declarar las condiciones de servicio, y 24 V bien medidos es exactamente eso.",
    },
    {
        "id": "T02",
        "name": "Reserva de corriente de diseño",
        "category": "Capacidad",
        "iec": "IEC 61439-1 §5.3 · corriente asignada del conjunto",
        "metric": "i_rms",
        "design_field": "in_diseno",
        "tolerance_pct": 10.0,
        "summary": "Contrasta la corriente RMS del CSV con In de prediseño y el margen que quieres dejar.",
        "fields": [
            _num("in_diseno", "In de prediseño", "A", 63.0, 1),
            _num("margen_pct", "Reserva deseada", "%", 20.0),
            _num("num_racks", "Racks alimentados", "", 4, 1),
            _sel("redundancia", "Redundancia", ["N", "N+1", "2N"], "N+1"),
        ],
        "voice": "La 61439 no te pide ir justo de corriente: te pide un In declarado con cabeza. Un margen del 20 % es el gesto elegante de un tablero que va a crecer con el CFT.",
    },
    {
        "id": "T03",
        "name": "Factor de potencia del nodo",
        "category": "Capacidad",
        "iec": "IEC 61439-1 §5 · datos de alimentación",
        "metric": "power_factor",
        "design_field": "fp_objetivo",
        "tolerance_pct": 8.0,
        "summary": "Si el CSV no trae P/Q, usa el FP declarado en el formulario y compáralo con el objetivo.",
        "fields": [
            _num("fp_objetivo", "FP objetivo", "", 0.92, 0.01),
            _num("fp_medido", "FP medido (si el CSV no lo trae)", "", 0.90, 0.01),
            _chk("carga_it", "Carga mayoritariamente IT / conmutada", True),
        ],
        "voice": "Declarar el factor de potencia en el prediseño es de esas cosas que la 61439-1 hace bien: el tablero deja de ser un dibujo y pasa a ser un modelo eléctrico.",
    },
    {
        "id": "T04",
        "name": "Frecuencia y estabilidad de red / bus",
        "category": "Medición",
        "iec": "IEC 61439-1 §5.2 tensión y frecuencia asignadas",
        "metric": "freq_hz",
        "design_field": "f_nom",
        "tolerance_pct": 2.0,
        "summary": "Estima frecuencia por cruces de cero si hay AC; en 24 VDC informa estabilidad del bus.",
        "fields": [
            _num("f_nom", "Frecuencia nominal (si AC)", "Hz", 50.0),
            _sel("sistema", "Sistema observado", ["24 VDC rack", "230/400 VAC", "mixto"], "24 VDC rack"),
            _num("desvio_max_hz", "Desvío máximo AC", "Hz", 0.5),
        ],
        "voice": "En continua no hay 50 Hz que defender; hay un rizado que contar. En alterna, la 61439 te pide Ue y f en la placa. Los dos mundos caben en el mismo expediente.",
    },
    {
        "id": "T05",
        "name": "THDi y cargas no lineales",
        "category": "Armónicos",
        "iec": "IEC 61439-1 §10.10 pérdidas · RIC 04 neutro",
        "metric": "thdi",
        "design_field": "thdi_umbral",
        "tolerance_pct": 15.0,
        "summary": "Compara THDi académico (formulario o campaña AC) con el umbral de diseño y el flag de carga armónica.",
        "fields": [
            _num("thdi_umbral", "Umbral de trabajo THDi", "%", 8.0),
            _num("thdi_medido", "THDi si no viene en el CSV", "%", 12.0),
            _chk("carga_armonica", "Prediseño con carga armónica activada", False),
            _sel("neutro", "Criterio de neutro", ["1.0 × fase", "1.5 × fase (RIC 04)"], "1.5 × fase (RIC 04)"),
        ],
        "voice": "La 61439 no sustituye un analizador de red, pero sí te obliga a meter las pérdidas extra en el calentamiento. Activar carga armónica en el TAN es el gesto correcto cuando el IT del CFT deja de ser lineal.",
    },
    {
        "id": "T06",
        "name": "Corriente de cortocircuito Icc",
        "category": "Protección",
        "iec": "IEC 61439-1 §10.11 resistencia a cortocircuitos",
        "metric": "icc_ka",
        "design_field": "icc_diseno",
        "tolerance_pct": 10.0,
        "summary": "Contrasta Icc de sitio (formulario) con Icw/Icc de la envolvente prevista.",
        "fields": [
            _num("icc_diseno", "Icc de prediseño", "kA", 10.0),
            _num("icc_sitio", "Icc informada del sitio", "kA", 8.0),
            _num("icw_envolvente", "Icw de catálogo XL³", "kA", 25.0),
            _txt("origen_icc", "Origen del dato de sitio", "memoria de cálculo / distribuidora"),
        ],
        "voice": "El §10.11 es de las joyas de la 61439: no improvisas el cortocircuito. Si el CSV no lo mide, el formulario deja el número sobre la mesa y el catálogo XL³ responde con Icw.",
    },
    {
        "id": "T07",
        "name": "Corriente de corta duración Icw",
        "category": "Protección",
        "iec": "IEC 61439-1 §10.11 · IEC 61439-2 conjuntos de potencia",
        "metric": "icw_ka",
        "design_field": "icw_req",
        "tolerance_pct": 5.0,
        "summary": "Verifica que Icw de envolvente cubra la Icw requerida del prediseño.",
        "fields": [
            _num("icw_req", "Icw requerida", "kA", 10.0),
            _num("icw_catalogo", "Icw de la envolvente", "kA", 25.0),
            _num("t_s", "Duración de referencia", "s", 1.0),
            _sel("familia", "Familia TAN", ["TT-S", "TT-M", "TT-E"], "TT-S"),
        ],
        "voice": "Icw es el número que separa un tablero pensado de uno que solo 'parece' robusto. La 61439-2 te deja elegir conjunto; el catálogo te dice si esa elección aguanta.",
    },
    {
        "id": "T08",
        "name": "Calentamiento y ΔT de envolvente",
        "category": "Térmico",
        "iec": "IEC 61439-1 §10.10 límites de calentamiento",
        "metric": "delta_t",
        "design_field": "delta_t_lim",
        "tolerance_pct": 10.0,
        "summary": "Compara ΔT estimado (formulario / TAN) con el límite de 30 °C de referencia del prediseño.",
        "fields": [
            _num("delta_t_lim", "Límite ΔT de referencia", "°C", 30.0),
            _num("delta_t_est", "ΔT estimado del prediseño", "°C", 18.0),
            _num("p_loss", "Pérdidas estimadas", "W", 120.0),
            _sel("ventilacion", "Ventilación", ["natural", "forzada", "sala climatizada"], "natural"),
        ],
        "voice": "El §10.10 es el capítulo que te ahorra el tablero que 'calienta raro'. 30 °C de referencia no es dogma de ensayo de tipo: es una brújula de prediseño, y se agradece.",
    },
    {
        "id": "T09",
        "name": "Equilibrio de fases en distribución",
        "category": "Distribución",
        "iec": "IEC 61439-1 §5 · circuitos de distribución",
        "metric": "unbalance_pct",
        "design_field": "unbalance_max",
        "tolerance_pct": 20.0,
        "summary": "Si hay Ia/Ib/Ic en el CSV, mide desequilibrio; si no, usa corrientes declaradas.",
        "fields": [
            _num("unbalance_max", "Desequilibrio máximo", "%", 10.0),
            _num("ia_decl", "Ia declarada si falta CSV 3F", "A", 0.0),
            _num("ib_decl", "Ib declarada", "A", 0.0),
            _num("ic_decl", "Ic declarada", "A", 0.0),
        ],
        "voice": "Un rack CFT desbalanceado no se ve en el unifilar; se ve en el neutro. La 61439 te invita a tratar las salidas como un sistema, no como tres tomas sueltas.",
    },
    {
        "id": "T10",
        "name": "Neutro y tercer armónico",
        "category": "Armónicos",
        "iec": "IEC 61439-1 §10.10 · RIC 04 p.5.3",
        "metric": "in_rms",
        "design_field": "in_limite",
        "tolerance_pct": 15.0,
        "summary": "Relaciona In de campaña con el criterio 1.5 × fase cuando hay IT / H3.",
        "fields": [
            _num("i_fase", "Corriente de fase de diseño", "A", 40.0),
            _num("in_limite", "In máxima de trabajo", "A", 60.0),
            _chk("carga_it", "Cargas monofásicas conmutadas", True),
            _sel("seccion_n", "Sección de neutro", ["igual a fase", "150 % de fase"], "150 % de fase"),
        ],
        "voice": "El neutro gordo no es lujo: con H3 es higiene. RIC 04 y la 61439 se llevan bien cuando dejas constancia de que el IT del laboratorio no es una resistencia pura.",
    },
    {
        "id": "T11",
        "name": "Dimensionamiento del alimentador",
        "category": "Capacidad",
        "iec": "IEC 61439-1 §10.8 bornes para conductores externos",
        "metric": "i_rms",
        "design_field": "iz_conductor",
        "tolerance_pct": 10.0,
        "summary": "Compara corriente medida/declarada con Iz del alimentador previsto.",
        "fields": [
            _num("iz_conductor", "Iz del alimentador", "A", 80.0, 1),
            _sel("material", "Material", ["Cu", "Al"], "Cu"),
            _num("seccion_mm2", "Sección", "mm²", 16.0, 1),
            _num("caida_pct", "Caída de tensión máxima", "%", 3.0),
        ],
        "voice": "El §10.8 te recuerda que el tablero termina en bornes reales, no en una flecha de AutoCAD. Iz y sección son la cortesía mínima hacia el cable que llega del cubículo.",
    },
    {
        "id": "T12",
        "name": "Coordinación de protecciones",
        "category": "Protección",
        "iec": "IEC 61439-2 · integración de aparatos §10.6",
        "metric": "i_rms",
        "design_field": "in_interruptor",
        "tolerance_pct": 12.0,
        "summary": "Ubica la corriente de trabajo respecto de In del interruptor y su curva.",
        "fields": [
            _num("in_interruptor", "In del interruptor", "A", 63.0, 1),
            _sel("curva", "Curva", ["C", "D", "K", "otro"], "C"),
            _num("icu", "Icu declarada", "kA", 10.0),
            _chk("selectividad", "Selectividad estudiada con el tablero aguas arriba", False),
        ],
        "voice": "Coordinar protecciones es el arte de que abra quien debe. La 61439-2 no te hace el estudio de selectividad, pero te exige que los aparatos convivan en un conjunto declarado.",
    },
    {
        "id": "T13",
        "name": "Forma de separación interna",
        "category": "Configuración",
        "iec": "IEC 61439-2 formas 1 a 4b",
        "metric": "forma_score",
        "design_field": "forma_objetivo",
        "tolerance_pct": 0.0,
        "summary": "Contrasta la forma prevista (2b/3b/4) con criticidad del nodo CFT.",
        "fields": [
            _sel("forma_actual", "Forma actual / prevista", ["1", "2b", "3b", "4a", "4b"], "2b"),
            _sel("forma_objetivo", "Forma objetivo", ["2b", "3b", "4a", "4b"], "3b"),
            _sel("sla", "SLA del nodo", ["aula / laboratorio", "nodo de piso", "nodo crítico"], "aula / laboratorio"),
            _chk("intervencion_en_caliente", "Se interviene con otras UF energizadas", False),
        ],
        "voice": "La forma de separación es la 61439-2 en estado puro: decides cuánto puedes tocar una UF sin saludar a todas las demás. En un CFT, 2b suele ser elegante; 3b brilla cuando el nodo no puede parar.",
    },
    {
        "id": "T14",
        "name": "Grado de protección IP",
        "category": "Configuración",
        "iec": "IEC 61439-1 §10.3 grado IP",
        "metric": "ip",
        "design_field": "ip_min",
        "tolerance_pct": 0.0,
        "summary": "Compara IP de envolvente con el mínimo del sitio (polvo, pasillo, exterior cubierto).",
        "fields": [
            _num("ip_min", "IP mínimo del sitio", "", 54, 1),
            _num("ip_catalogo", "IP de la envolvente elegida", "", 54, 1),
            _sel("ambiente", "Ambiente", ["sala técnica", "taller / pañol", "pasillo", "exterior cubierto"], "sala técnica"),
            _chk("condensacion", "Riesgo de condensación", False),
        ],
        "voice": "IP no es un sticker: es cómo el conjunto respira y se defiende. El §10.3 te deja elegir con honestidad el ambiente del CFT, no el de un catálogo europeo de vitrina.",
    },
    {
        "id": "T15",
        "name": "Ventilación y disipación en sala",
        "category": "Térmico",
        "iec": "IEC 61439-1 §10.10 · condiciones de instalación",
        "metric": "delta_t",
        "design_field": "delta_t_lim",
        "tolerance_pct": 12.0,
        "summary": "Cruza pérdidas del tablero con la capacidad de la sala / rack.",
        "fields": [
            _num("delta_t_lim", "ΔT máximo de trabajo", "°C", 30.0),
            _num("t_sala", "Temperatura de sala", "°C", 25.0),
            _num("p_loss", "Pérdidas del conjunto", "W", 150.0),
            _sel("flujo", "Flujo de aire", ["natural", "forzado en tablero", "HVAC de sala"], "HVAC de sala"),
        ],
        "voice": "Un XL³ impecable en una sala sin aire es un malentendido. La 61439 te pide las condiciones de servicio: temperatura ambiente, no solo el aluminio de la envolvente.",
    },
    {
        "id": "T16",
        "name": "Capacidad de barras colectoras",
        "category": "Distribución",
        "iec": "IEC 61439-1 §10.11 · §10.10",
        "metric": "i_rms",
        "design_field": "i_barra",
        "tolerance_pct": 8.0,
        "summary": "Ubica la corriente de trabajo respecto de la corriente asignada de barras.",
        "fields": [
            _num("i_barra", "Corriente asignada de barras", "A", 160.0, 1),
            _num("in_conjunto", "In del conjunto", "A", 125.0, 1),
            _sel("tipo_barra", "Tipo", ["plana Cu", "perfil XL³", "cableada"], "perfil XL³"),
            _chk("derivaciones_calientes", "Muchas derivaciones en un mismo tramo", False),
        ],
        "voice": "Las barras son el esqueleto. La 61439 te deja dimensionarlas como sistema verificado de fabricante: menos artesanía, más conjunto.",
    },
    {
        "id": "T17",
        "name": "Redistribución de cargas entre racks",
        "category": "Distribución",
        "iec": "IEC 61439-1 corriente asignada de circuitos",
        "metric": "i_rms",
        "design_field": "i_por_rack",
        "tolerance_pct": 15.0,
        "summary": "Compara la campaña con la corriente media por rack y propone repartir.",
        "fields": [
            _num("num_racks", "Número de racks", "", 6, 1),
            _num("i_por_rack", "Corriente objetivo por rack", "A", 10.0),
            _num("racks_criticos", "Racks que no pueden bajar carga", "", 1, 1),
            _txt("notas_carga", "Notas de ocupación", "aula + servidor de piso"),
        ],
        "voice": "A veces la solución no es un tablero más grande: es dejar de alimentar tres racks gordos por un solo ramal. La 61439 te da In por circuito; el CFT te da el mapa real de ocupación.",
    },
    {
        "id": "T18",
        "name": "Mitigación armónica (AHF / prediseño)",
        "category": "Armónicos",
        "iec": "IEC 61439-1 pérdidas · prediseño TAN + AHF académico",
        "metric": "thdi",
        "design_field": "thdi_objetivo",
        "tolerance_pct": 20.0,
        "summary": "Usa THDi de campaña o del Monitor AHF y sugiere si el prediseño debe llevar compensación.",
        "fields": [
            _num("thdi_objetivo", "THDi objetivo de trabajo", "%", 8.0),
            _num("i_comp", "I de compensación estimada", "A", 15.0),
            _chk("ahf_previsto", "Se contempla módulo AHF en el nodo", False),
            _sel("estrategia", "Estrategia", ["prediseño con flag armónico", "AHF dedicado", "redistribuir IT"], "prediseño con flag armónico"),
        ],
        "voice": "El AHF de este software es académico y se nota: sirve para dimensionar la conversación, no para inyectar amperios. La 61439 entra cuando esas pérdidas se traducen en calentamiento y en un BOM con neutro en serio.",
    },
    {
        "id": "T19",
        "name": "Configuración de la medición (CSV del scope)",
        "category": "Medición",
        "iec": "IEC 61439-1 datos de entrada del conjunto",
        "metric": "v_mean",
        "design_field": "v_nom",
        "tolerance_pct": 5.0,
        "summary": "Revisa mapeo CH1/CH2, acoplamiento y si el CSV cuenta la historia correcta del rack.",
        "fields": [
            _num("v_nom", "Magnitud esperada en CH1", "V", 24.0),
            _sel("mapeo", "Mapeo propuesto", ["CH1 → va (24 V)", "CH1 → ia", "CH1 va / CH2 ia"], "CH1 → va (24 V)"),
            _sel("acoplo", "Acoplamiento", ["DC", "AC", "AC+DC"], "DC"),
            _txt("instrumento", "Instrumento", "Gratten GA1102CAL"),
        ],
        "voice": "Un CSV bien mapeado vale más que un ensayo mal contado. La 61439 se alimenta de datos de servicio: si CH1 era 24 V y lo leíste como corriente, el tablero 'cumple' un problema que no existe.",
    },
    {
        "id": "T20",
        "name": "Campaña antes / después",
        "category": "Medición",
        "iec": "IEC 61439-1 trazabilidad de condiciones de servicio",
        "metric": "delta_campaigns",
        "design_field": "mejora_min_pct",
        "tolerance_pct": 5.0,
        "summary": "Compara dos CSV del mismo punto: intervención, redistribución o cambio de fuente.",
        "fields": [
            _num("mejora_min_pct", "Mejora mínima esperada", "%", 10.0),
            _sel("eje", "Eje de comparación", ["tensión media", "rizado", "RMS de corriente", "THDi declarado"], "tensión media"),
            _txt("intervencion", "Qué cambió entre campañas", "ajuste de Ilim / redistribución de rack"),
            _chk("mismo_punto", "Mismo punto de medida y misma escala", True),
        ],
        "voice": "Dos CSV del mismo bornes son un lujo de laboratorio. La 61439 aprecia las condiciones de servicio documentadas: antes y después es la forma adulta de decir que algo mejoró.",
    },
    {
        "id": "T21",
        "name": "Hipótesis de proyecto (potencia, racks, IP)",
        "category": "Documentación",
        "iec": "IEC 61439-1 datos del conjunto · placa de características",
        "metric": "v_mean",
        "design_field": "v_nom",
        "tolerance_pct": 8.0,
        "summary": "Cruza lo medido con las hipótesis del formulario TAN: potencia, racks, IP, armónicos.",
        "fields": [
            _num("v_nom", "Ue de cálculo / bus", "V", 24.0),
            _num("potencia_kw", "Potencia declarada", "kW", 45.0),
            _num("num_racks", "Racks", "", 4, 1),
            _num("ip_minimo", "IP mínimo declarado", "", 54, 1),
            _chk("carga_armonica", "Hipótesis de carga armónica", False),
        ],
        "voice": "Las hipótesis son el contrato interno del prediseño. La 61439-1 te pide Ue, In, IP en la placa: este formulario es el borrador honesto de esa placa.",
    },
    {
        "id": "T22",
        "name": "Actualizar el modelo TAN",
        "category": "Documentación",
        "iec": "IEC 61439-1 conjunto como sistema documentado",
        "metric": "i_rms",
        "design_field": "in_diseno",
        "tolerance_pct": 10.0,
        "summary": "Si la campaña se alejó del prediseño, lista qué inputs TAN conviene recalcular.",
        "fields": [
            _num("in_diseno", "In actual en el modelo", "A", 63.0, 1),
            _num("potencia_kw", "Potencia actual en el modelo", "kW", 45.0),
            _chk("recalcular_envolvente", "Recalcular envolvente XL³", True),
            _chk("recalcular_forma", "Revisar forma de separación", False),
        ],
        "voice": "Un modelo TAN que no se actualiza envejece mal. La 61439 entiende el conjunto como un expediente vivo: números nuevos, misma disciplina.",
    },
    {
        "id": "T23",
        "name": "Revisión de ingeniería (cambio controlado)",
        "category": "Documentación",
        "iec": "IEC 61439-1 / -2 expediente del conjunto",
        "metric": "delta_campaigns",
        "design_field": "mejora_min_pct",
        "tolerance_pct": 5.0,
        "summary": "Arma una revisión: qué cambió, qué se propone y qué queda pendiente de laboratorio.",
        "fields": [
            _num("mejora_min_pct", "Umbral para cerrar la revisión", "%", 5.0),
            _txt("motivo", "Motivo de la revisión", "ampliación de racks de aula"),
            _txt("responsable", "Responsable técnico", "Andres Barbudo Rodriguez"),
            _sel("urgencia", "Urgencia", ["programada", "antes de defensa", "operativa"], "programada"),
        ],
        "voice": "Revisar no es admitir derrota: es el modo 61439 de crecer. Dejas rastro, comparas CSV y sales con un prediseño que todavía se puede explicar.",
    },
    {
        "id": "T24",
        "name": "Bitácora y revisión experta",
        "category": "Documentación",
        "iec": "IEC 61439-1 verificación de diseño y de rutina",
        "metric": "v_mean",
        "design_field": "v_nom",
        "tolerance_pct": 5.0,
        "summary": "Cierra el caso con observaciones de pañol, CSV adjuntos y próximos pasos humanos.",
        "fields": [
            _num("v_nom", "Valor de referencia", "V", 24.0),
            _txt("observador", "Quién midió", "laboratorio CFT Paillaco"),
            _txt("hallazgos", "Hallazgos de pañol", ""),
            _sel("siguiente", "Siguiente paso", ["repetir CSV", "recalcular TAN", "visita de guía", "cerrar caso"], "repetir CSV"),
        ],
        "voice": "Hay decisiones que un CSV no toma solo, y está bien. La 61439 distingue verificación de diseño y de rutina: esta plantilla es el puente entre el archivo y la persona que estuvo en el pañol.",
    },
]


def get_templates() -> list[dict[str, Any]]:
    return TEMPLATES


def get_template(template_id: str) -> dict[str, Any]:
    for item in TEMPLATES:
        if item["id"] == template_id:
            return item
    raise KeyError(template_id)
